# Generated by Django 6.0 on 2026-01-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
